"""init_tables

Revision ID: 2045a876c91e
Revises: b1c84623bada
Create Date: 2026-06-17 21:15:44.352314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2045a876c91e'
down_revision: Union[str, None] = 'b1c84623bada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('client_company', sa.String(), nullable=False),
    sa.Column('time_left_home', sa.DateTime(), nullable=False),
    sa.Column('time_reached_company', sa.DateTime(), nullable=True),
    sa.Column('time_finished_company', sa.DateTime(), nullable=True),
    sa.Column('time_reached_home', sa.DateTime(), nullable=False),
    sa.Column('km_driven', sa.Float(), nullable=False),
    sa.Column('overnight_stay', sa.Boolean(), nullable=False),
    sa.Column('only_travel_day', sa.Boolean(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('premium_hours', sa.Float(), nullable=False),
    sa.Column('taxable_wages', sa.Float(), nullable=False),
    sa.Column('tax_free_reimbursements', sa.Float(), nullable=False),
    sa.Column('total_take_home', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
